# https://taskfile.dev
version: '3'


tasks:
  build:
    desc: build binary
    env:
      CGO_ENABLED: 0
    vars:
      GITHASH:
        sh: git rev-parse --short HEAD
      GITTAG:
        sh: git tag -l --points-at HEAD
      GITBRANCH:
        sh: git rev-parse --abbrev-ref HEAD
    sources:
    - "**/*.go"
    generates:
      - gha-cli
    cmds:
    - |
      go build -ldflags "-extldflags '-static'
      -X 'github.com/Norsk-Tipping/gha-cli/cmd.GitHash={{.GITHASH}}'
      -X 'github.com/Norsk-Tipping/gha-cli/cmd.GitTag={{.GITTAG}}'
      -X 'github.com/Norsk-Tipping/gha-cli/cmd.GitBranch={{.GITBRANCH}}'"


  setup:
    desc: install dependencies
    cmds:
      - go mod tidy

  test:
    desc: run tests
    cmds:
      - go vet ./...
      - go test ./... -covermode=atomic -coverpkg=./... -coverprofile=coverage.txt

  cover:
    desc: open the cover tool
    cmds:
      - go tool cover -html=coverage.txt

  default:
    cmds:
      - task: setup
      - task: test
      - task: build
